-- Day 19: Creating relational table schemas with explicit constraints for User Roles
-- Topic: Enterprise Oracle DB Constraints & Schema Design

CREATE TABLE sec_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    user_role VARCHAR2(20) NOT NULL,
    
    -- Primary and Unique constraints protect identity states
    CONSTRAINT pk_sec_users PRIMARY KEY (id),
    CONSTRAINT uq_sec_username UNIQUE (username),
    
    -- Check Constraint ensures no invalid string can ever be inserted into the role column
    CONSTRAINT chk_user_role CHECK (user_role IN ('ADMIN', 'USER', 'MANAGER'))
);

-- Seed data to verify that valid role inputs commit perfectly
INSERT INTO sec_users (username, password, user_role) 
VALUES ('admin_rahul', '$2a$10$xyzFakeBcryptHashTextLine...', 'ADMIN');

COMMIT;

-- Benefit: Relying solely on frontend or backend application code for data safety is risky. 
-- Adding a CHECK constraint directly into the Oracle table ensures that even if a bug occurs 
-- in Java or React, the database will instantly block corrupt or typo-ridden roles from being saved.
